### ISSUE TITLE
TCP/TLS connect failure

### ISSUE THREAD

**Issue by tparvais** [FragJage/MqttDaemon#2]
Hello

Thank you for the soft.

I properly compiled MqttOwfs on my Pi-0w.
I'm running owserver and owfs without problem
Mqtt mosquito is on another host 192.168.0.2 port 1883. 

When launchiong MqttOwfs -console, I get

MQTT error [-1]: TCP/TLS connect failure

But I need to add MQTT login/Password : where/how can I do it ?

**Comment by FragJage** [comment]
It's a bug, mqtt provider must be on the same host.

**Comment by FragJage** [comment]
It's now possible to use a mqtt provider on an other host.
New feature : user and password can be add in config file, mqtt section.
